### ISSUE TITLE
Different Spectronaut output format

### ISSUE THREAD

**Issue by HaoZhang17** [tvpham/iq#1]
Hi,

For the DIA quantification data, the long-format output I got from Spectronaut contains ProteinName, PeptideSequence, PrecursorCharge, FragmentIon, ProductCharge, IsotopeLabelType, Condition, BioReplicate, Run, Intensity, and F.ExcludedFromQuantification. It can be directly imported into MSstats, but it seems that this format does not meet the demand. How can I change this format?

Thanks in advance!

**Comment by tvpham** [comment]
Hi Hao Zhang,

Can you consult https://cran.r-project.org/web/packages/iq/vignettes/iq-fast.html to see if you can set the input appropriately?

There is more information in the help page of the preprocess function. Thus, you could try ?preprocess .

sample_id is the column containing the samples which will be the column names of the final report. It could be "Condition" or "Run" in your case. You can check the head of your long-format export.

secondary_id is likely to be c("PeptideSequence", "PrecursorCharge", "FragmentIon", "ProductCharge")

primary_id should "ProteinName" . The default value is "PG.ProteinGroups" from our version of Spectronaut.

Finally, intensity_col should be "Intensity". Default value is "F.PeakArea".


Thang
