### ISSUE TITLE
Spectronaut hybrid

### ISSUE THREAD

**Issue by AUldry** [tvpham/iq#19]
Dear Thang,

I've always been somewhat puzzled by the Spectronaut (SN) protein normalisation and quantifications and am quite eager to test alternative procedures. Your SN application examples, if I am not mistaken, are using SN results obtained by spectral library. Would you say that the ir package is equally applicable on SN results obtained via library-free/hybrid/deep+ approaches?

**Comment by tvpham** [comment]
yes, it is equally applicable.

Thang

**Comment by AUldry** [comment]
Thanks for the swift reply (and the iq package)!
