### ISSUE TITLE
iq availability on CRAN?

### ISSUE THREAD

**Issue by jpquast** [tvpham/iq#2]
Hey! I have seen that the `iq` package is not available on CRAN anymore. Do you plan to make it available through CRAN again or will it only stay available through the GitHub repository?
Thanks!

**Comment by tvpham** [comment]
Hi, the package should be back on CRAN soon (We were not aware that the authors of Eigen should be in the Author list of the packge). I submitted a revision last Friday, and it should take around 5 working days if all is well.
Cheers.

**Comment by tvpham** [comment]
Hi, just a quick update. We need to substantially revise the CRAN submission. Installation from GitHub should work

devtools::install_github("tvpham/iq") 

We are working on getting iq back on CRAN so that compilation is not required.

**Comment by tvpham** [comment]
iq is back on CRAN.
