### ISSUE TITLE
process_long_format function for DIA-NN output not available in R

### ISSUE THREAD

**Issue by Yi-Wo** [tvpham/iq#4]
Hi, 

I am currently running this package in R4.2, I'm not sure if I'm doing something wrong but I have not been able to process the DIA-NN output/report file in this package as the function in your readme is not available and I'm not sure what other functions I should use in this package. 

Thank you.

**Comment by tvpham** [comment]
Hi Yi-Wo, 
Perhaps you are not using the latest version of iq. The process_long_format function is only available from version 1.9.6.
Thang
